App\Symfony\Entity\Recipe:
    type: entity
    repositoryClass: 'App\Symfony\Repository\RecipesList'
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
        description:
            type: text
    oneToMany:
        ingredients:
            targetEntity: 'App\Symfony\Entity\QuantifiableIngredient'
            cascade: [all]
            mappedBy: 'recipe'
    manyToOne:
        createdBy:
            targetEntity: 'App\Symfony\Entity\User'
            inversedBy: 'recipes'
            cascade: [persist]

