app_recipes_index:
    path: /
    defaults:
        _controller: 'app.cookery.page.index'
    methods: [GET]

app_recipes_show:
    path: /{recipeIdentifier}
    defaults:
        _controller: 'app.cookery.page.show'
    methods: [GET]
    requirements:
        id: '\d+'

app_recipes_new:
    path: /new
    defaults:
        _controller: 'app.symfony.controller.recipes_controller:newAction'
    methods: [GET]

app_recipes_create:
    path: /
    defaults:
        _controller: 'app.symfony.controller.recipes_controller:newAction'
    methods: [POST]
