security:
    encoders:
        'App\Symfony\Entity\User':
            algorithm: sha512
    providers:
        app:
            entity:
                class: 'App:User'
                property: 'username'
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        app:
            anonymous: ~
            provider: app
