# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    app.symfony.controller.recipes_controller:
        class: App\Symfony\Controller\RecipesController
        arguments:
            - '@doctrine'
            - '@templating'
            - '@form.factory'
            - '@router'
            - '@security.token_storage'

    app.symfony.repository.recipes_list:
        class: App\Symfony\Repository\RecipesList
        factory:
            - '@doctrine.orm.entity_manager'
            - 'getRepository'
        arguments: ['App:Recipe']

    app.cookery.page.index:
        class: App\Cookery\Page\Index
        arguments:
            - '@app.symfony.repository.recipes_list'
            - '@templating'
